apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: dg0410-lifesub-ns
data:
  runtime-env.js: |
    window.__runtime_config__ = {
      MEMBER_URL: 'http://dg0410.20.249.184.228.nip.io/api/auth',
      MYSUB_URL: 'http://dg0410.20.249.184.228.nip.io/api/mysub',
      RECOMMEND_URL: 'http://dg0410.20.249.184.228.nip.io/api/recommend'
    };
