apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifesub-web
  namespace: dg0410-lifesub-ns
  labels:
    app: lifesub-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifesub-web
  template:
    metadata:
      labels:
        app: lifesub-web
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: lifesub-web
        image: acrdigitalgarage02.azurecr.io/dg0410/lifesub-web:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 18080
          name: http
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 1024m
            memory: 1024Mi
        volumeMounts:
        - name: runtime-config
          mountPath: /usr/share/nginx/html/runtime-env.js
          subPath: runtime-env.js
        livenessProbe:
          httpGet:
            path: /
            port: 18080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 18080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: runtime-config
        configMap:
          name: frontend-config
